### ISSUE TITLE
Status bar color on VS Code 1.50.0 seems to be broken?

### ISSUE THREAD

**Issue by quebin31** [rafaelmardojai/vscode-gnome-theme#3]
It should be dark, but it seems to be using the default VS Code status bar color.

Edit: Extra information, this only happens when there isn't an open folder, is this the expected behavior? 

![2020-10-12 (11:34:16)](https://user-images.githubusercontent.com/3249204/95770337-e148f680-0c7e-11eb-9bef-60674997b206.png)

**Comment by Micronetic** [comment]
Can confirm:
![image](https://user-images.githubusercontent.com/57453593/119002429-28be0080-b98d-11eb-8b82-82bc489e5245.png)

**Comment by rafaelmardojai** [comment]
Should be fixed in the new release `0.3.0`.
