### ISSUE TITLE
Publish the theme in OpenVSX Registry

### ISSUE THREAD

**Issue by jeffteixeira** [rafaelmardojai/vscode-gnome-theme#4]
This theme is only available for VSCode users. For those who use VSCodium, it is not. It would be a good idea to add this theme to the [OpenVSX Registry](https://open-vsx.org/), making it available to VSCodium users.
Tutorial for publish extension in OpenVSX registry: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by ghost** [comment]
> This theme is only available for VSCode users. For those who use VSCodium, it is not. It would be a good idea to add this theme to the [OpenVSX Registry](https://open-vsx.org/), making it available to VSCodium users.
> Tutorial for publish extension in OpenVSX registry: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

You can install this:
![image](https://user-images.githubusercontent.com/57453593/118304638-371ca000-b4e7-11eb-894c-5dd31aec2289.png)

**Comment by rafaelmardojai** [comment]
Finally I found some free time to do this, the theme it's now available in the [OpenVSX Registry](https://open-vsx.org/extension/rafaelmardojai/vscode-gnome-theme). 

For the record, remember you can find a `.vsix` in the [releases page](https://github.com/rafaelmardojai/vscode-gnome-theme/releases).
